### ISSUE TITLE
docker container 0.12.11 & 0.12.15: 100% cpu usage

### ISSUE THREAD

**Issue by gabriel-v** [SeekStorm/SeekStorm#39]
After a couple of days of having the docker container around, I found that it now is stuck on 100% CPU all the time (spinning a single core on machine).

Web UI and index functions are all still working, through the container always uses 100% CPU.

![Image](https://github.com/user-attachments/assets/ca7d351e-9ead-45af-8995-cf6dbdf08ba0)

Docker logs have no indication of problem.

```
✗ docker logs -f seekstorm 
SeekStorm server v0.12.15
Press CTRL-C or enter 'quit' to shutdown server, enter 'help' for console commands.
Ingest path: /
Listening on: 127.0.0.1:80 index dir /seekstorm_index master key A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=


```

### steps to reproduce
1. use docker on linux ( debian stable + kernel 6)
2. use this docker compose file

```
services:
  seekstorm:
    container_name: seekstorm
    image: wolfgarbe/seekstorm_server:v0.12.15
    volumes:
      - /seekstorm_index
    environment:
      - MASTER_KEY_SECRET=1234
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6000M
        reservations:
          cpus: '1'
          memory: 2000M
    restart: unless-stopped
    command: /seekstorm_server local_ip="127.0.0.1" local_port=80 index_path="/seekstorm_index"

```

3. start container and watch its CPU usage with `docker stats seekstorm`
4. observe permanent 100% CPU usage 

---

The "ingest path" as "/" seemed problematic, maybe this was scanning the root filesystem of the container for pdfs and texts? Let's try setting another dir

```
  seekstorm:
    container_name: seekstorm
    image: wolfgarbe/seekstorm_server:v0.12.15
    volumes:
      - /seekstorm_index
      - /seekstorm_ingest
      ...
    command: /seekstorm_server local_ip="127.0.0.1" local_port=80 index_path="/seekstorm_index" ingest_path="/seekstorm_ingest"
```

```
 ✗ docker logs seekstorm 
SeekStorm server v0.12.15
Press CTRL-C or enter 'quit' to shutdown server, enter 'help' for console commands.
Ingest path: /seekstorm_ingest
Listening on: 127.0.0.1:80 index dir /seekstorm_index master key A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=


```

```
CONTAINER ID   NAME        CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
6ca1d1625f99   seekstorm   100.76%   968KiB / 5.859GiB   0.02%     17.7kB / 0B   0B / 0B     6

```

Running this container still uses 100% CPU, problem persists. Both volumes attached are completely empty.
